### ISSUE TITLE
Terraform crash while applying dns_ptr_record

### ISSUE THREAD

**Issue by shibug** [terraform-providers/terraform-provider-dns#14]
Here is my resource
```
resource "dns_ptr_record" "lb_private_dns_ptr" {
  count = "${var.private_lb ? 1 : 0}"
  zone  = "23.10.in-addr.arpa."
  name  = "${format("%s.%s.", element(split(".", azurerm_lb.lb_private.private_ip_address), 3), element(split(".", azurerm_lb.lb_private.private_ip_address), 2))}"
  ptr   = "${format("%s%s", substr(var.env, 0, 1), var.role)}."
}
```
Here is the crash.log
https://gist.github.com/shibug/da428ae6a13365c2d4ac5b0b82652820

**Comment by apparentlymart** [comment]
Hi @shibug! Sorry for this crash and thanks for reporting it.

Here's the stack trace from the log, for easier reference:

```
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: panic: runtime error: invalid memory address or nil pointer dereference
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: [signal 0xc0000005 code=0x0 addr=0x20 pc=0x9ade8e]
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: goroutine 41 [running]:
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/miekg/dns.(*Msg).Insert(0xc04226b7b0, 0xc04226b6b0, 0x1, 0x1)
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/miekg/dns/update.go:71 +0x8e
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: github.com/terraform-providers/terraform-provider-dns/dns.resourceDnsPtrRecordUpdate(0xc0422435e0, 0xa64a40, 0xc0420e6640, 0x2, 0x2)
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-dns/dns/resource_dns_ptr_record.go:151 +0x94f
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: github.com/terraform-providers/terraform-provider-dns/dns.resourceDnsPtrRecordCreate(0xc0422435e0, 0xa64a40, 0xc0420e6640, 0x0, 0x0)
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-dns/dns/resource_dns_ptr_record.go:61 +0x457
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc042247e60, 0xc042244780, 0xc04230c180, 0xa64a40, 0xc0420e6640, 0x1, 0x28, 0xc0422fc660)
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x494
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc04224aa80, 0xc042244730, 0xc042244780, 0xc04230c180, 0x1690db0, 0x0, 0x0)
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0xa2
2017-09-19T17:07:16.112-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0420e98e0, 0xc042231c00, 0xc04230a1d0, 0x0, 0x0)
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-dns/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x5e
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: reflect.Value.call(0xc0421fe180, 0xc0420ea3c0, 0x13, 0xb7c38e, 0x4, 0xc042237f20, 0x3, 0x3, 0xc0420f1760, 0xa72840, ...)
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/usr/local/go/src/reflect/value.go:434 +0x926
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: reflect.Value.Call(0xc0421fe180, 0xc0420ea3c0, 0x13, 0xc042237f20, 0x3, 0x3, 0xc0421618f0, 0x0, 0x0)
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/usr/local/go/src/reflect/value.go:302 +0xab
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: net/rpc.(*service).call(0xc0422ee0c0, 0xc0422ee080, 0xc0422c61a8, 0xc04224e900, 0xc0422f61e0, 0xa66580, 0xc042231c00, 0x16, 0xa665c0, 0xc04230a1d0, ...)
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/usr/local/go/src/net/rpc/server.go:387 +0x14b
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: created by net/rpc.(*Server).ServeCodec
2017-09-19T17:07:16.113-0500 [DEBUG] plugin.terraform-provider-dns_v0.1.0_x4.exe: 	/usr/local/go/src/net/rpc/server.go:481 +0x40b
```

**Comment by shibug** [comment]
Glad to help. Let me know if you need anything from me. Meanwhile I am not creating PTR records.

**Comment by katbyte** [comment]
Hello @shibug,

Sorry to see your having this issue. As its been over 8 months just checking to see if this is still a problem with the latest version of the provider? If so could you please supply a fully working terraform example exhibiting the issue? The terraform above is sourcing data from a var that has not been supplied. Thanks!

**Comment by shibug** [comment]
I will verify it tomorrow.

**Comment by shibug** [comment]
You may close this issue.  It has been resolved.  The issue was with an ending . on name field

**Comment by katbyte** [comment]
Thank you for checking, glad to hear it has been resolved!
